nodeLinker: node-modules
packageExtensions:
  '@storybook/addon-docs@*':
    peerDependencies:
      '@types/react': '*'
  '@storybook/addon-vitest@*':
    peerDependencies:
      react: '*'
      react-dom: '*'
  '@storybook/react-vite@*':
    peerDependencies:
      typescript: '*'
  'cssstyle@*':
    peerDependencies:
      postcss: '*'
  'eslint-plugin-formatjs@*':
    peerDependencies:
      typescript: '*'
  'eslint-plugin-storybook@*':
    peerDependencies:
      typescript: '*'
  'jsdom@*':
    dependencies:
      postcss: '*'
  'storybook@*':
    peerDependencies:
      '@testing-library/dom': '*'
      react: '*'
      react-dom: '*'
